var hierarchy =
[
    [ "Animation2D.ani", "class_animation2_d_1_1ani.html", null ],
    [ "GameEventManager", "class_game_event_manager.html", null ],
    [ "MissionTemplate", "class_mission_template.html", null ],
    [ "MonoBehaviour", null, [
      [ "Animation2D", "class_animation2_d.html", null ],
      [ "AttackFireball", "class_attack_fireball.html", null ],
      [ "CoinMagnet", "class_coin_magnet.html", null ],
      [ "DemoLevel", "class_demo_level.html", null ],
      [ "DisablePlateform", "class_disable_plateform.html", null ],
      [ "Follow", "class_follow.html", null ],
      [ "GameObjectInstaniate", "class_game_object_instaniate.html", null ],
      [ "GUIManager", "class_g_u_i_manager.html", null ],
      [ "HelperFadeout", "class_helper_fadeout.html", null ],
      [ "HelperJumpPad", "class_helper_jump_pad.html", null ],
      [ "HelperPlatform", "class_helper_platform.html", null ],
      [ "HelperProjectile", "class_helper_projectile.html", null ],
      [ "HelperRotate", "class_helper_rotate.html", null ],
      [ "HudFPS", "class_hud_f_p_s.html", null ],
      [ "InputManager", "class_input_manager.html", null ],
      [ "LaserBeam", "class_laser_beam.html", null ],
      [ "LevelEdge", "class_level_edge.html", null ],
      [ "LevelGenerator", "class_level_generator.html", null ],
      [ "LevelManager", "class_level_manager.html", null ],
      [ "MissionManager", "class_mission_manager.html", null ],
      [ "Obstacles", "class_obstacles.html", null ],
      [ "PlayerAttack", "class_player_attack.html", null ],
      [ "PlayerCamera", "class_player_camera.html", null ],
      [ "PlayerDead", "class_player_dead.html", null ],
      [ "PlayerHealth", "class_player_health.html", null ],
      [ "PlayerJumping", "class_player_jumping.html", null ],
      [ "PlayerManager", "class_player_manager.html", null ],
      [ "PlayerMovement", "class_player_movement.html", null ],
      [ "PlayerOneWay", "class_player_one_way.html", null ],
      [ "PlayerPickups", "class_player_pickups.html", null ],
      [ "PlayerUI", "class_player_u_i.html", null ],
      [ "PowerUp", "class_power_up.html", null ],
      [ "PowerUpMain", "class_power_up_main.html", null ],
      [ "ResolutionManager", "class_resolution_manager.html", null ],
      [ "ScrollingObject", "class_scrolling_object.html", null ],
      [ "SonicWave", "class_sonic_wave.html", null ],
      [ "SortingLayer", "class_sorting_layer.html", null ],
      [ "SpriteAnim", "class_sprite_anim.html", null ],
      [ "Torpedo", "class_torpedo.html", null ],
      [ "TorpedoIndicator", "class_torpedo_indicator.html", null ],
      [ "TorpedoMain", "class_torpedo_main.html", null ],
      [ "TriggerAttack", "class_trigger_attack.html", null ],
      [ "TriggerCamera", "class_trigger_camera.html", null ],
      [ "TriggerDeadZone", "class_trigger_dead_zone.html", null ],
      [ "TriggerGoal", "class_trigger_goal.html", null ],
      [ "TriggerPickupItem", "class_trigger_pickup_item.html", null ],
      [ "TriggerRespawner", "class_trigger_respawner.html", null ]
    ] ],
    [ "object", null, [
      [ "SaveManager", "class_save_manager.html", null ]
    ] ]
];